# Generated by Django 5.0.1 on 2024-01-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department_Name',
            new_name='Department_Id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Position',
            new_name='Position_Id',
        ),
    ]
