# Generated by Django 5.0.1 on 2024-01-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_rename_department_name_employee_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='Poition_Id',
            new_name='Position_Id',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Position',
            new_name='Position_Name',
        ),
    ]
