# Generated by Django 5.0.1 on 2024-01-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_rename_poition_id_position_position_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department_Id',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Position_Id',
            new_name='Position',
        ),
    ]
