# Generated by Django 5.0.1 on 2024-01-16 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_runner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Runner',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
