# Generated by Django 5.0.1 on 2024-01-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_delete_runner_employee_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender',
            new_name='Gender',
        ),
    ]
